(use-package telega
  :hook
  ('telega-chat-mode . (lambda ()
                         (set (make-local-variable 'company-backends)
                              (append '(telega-company-emoji
                                        telega-company-username
                                        telega-company-hashtag)
                                      (when (telega-chat-bot-p telega-chatbuf--chat)
                                        '(telega-company-botcmd))))
                         (company-mode 1)
                         (linum-mode -1)
                         (emojify-mode)
                         )
                     )
  ('telega-root-mode . (lambda () 
                         (emojify-mode)
                         (linum-mode -1)
                         ))

  :config
  (defun weiss-telega-command-mode-define-keys ()
  (weiss--define-keys
   xah-fly-key-map
   '(
     ;; ("~" . nil)
     ;; (":" . nil)

     ;; ("SPC" . xah-fly-leader-key-map)
     ;; ("DEL" . xah-fly-leader-key-map)
     ;;   ("RET" . newline)

     ;; ("'" . xah-cycle-hyphen-underscore-space)
     ;; ("," . xah-pop-local-mark-ring)
     ;; ("-" . outline-show-entry)
     ;; ("=" . color-outline-toggle-all)
     ;; ("." . xah-forward-right-bracket)
     ;; (";" . xah-end-of-line-or-block)
     ;; ("/" . xah-goto-matching-bracket)
     ;; ("\\" . nil)
     ;; ("[" . hs-toggle-hiding)
     ;; ("]" . hs-hide-all)
     ;; ("}" . hs-show-all)
     ;; ("`" . other-frame)

     ;; ("<backtab>" . weiss-indent)
     ;; ("V" . weiss-paste-with-linebreak)
     ;; ("!" . rotate-text)
     ;; ("#" . xah-backward-quote)
     ;; ("$" . xah-forward-punct)

     ;; ("1" . scroll-down)
     ;; ("2" . scroll-up)
     ;; ("3" . delete-other-windows)
     ;; ("4" . split-window-below)
     ;; ("5" . delete-char)
     ;; ("6" . xah-select-block)
     ;; ("7" . xah-select-line)
     ;; ("8" . xah-extend-selection)
     ;; ("9" . xah-select-text-in-quote)
     ;; ("0" . xah-next-window-or-frame)

     ;; ("a" . open-line-and-indent)
     ;; ("b" . xah-toggle-letter-case)
     ;; ("c" . xah-copy-line-or-region)
     ;; ("d" . xah-delete-backward-char-or-bracket-text)
     ;; ("e" . xah-backward-kill-word)
     ;; ("f" . xah-fly-insert-mode-activate)
     ("g" . telega-chat-with)
     ;; ("h" . backward-char)
     ;; ("i" . xah-beginning-of-line-or-block)
     ;; ("j" . next-line)
     ;; ("k" . previous-line)
     ;; ("l" . forward-char)
     ;; ("m" . xah-backward-left-bracket)
     ("n" . next-line)
     ;; ("o" . forward-word)
     ("p" . previous-line)
     ;; ("q" . weiss-replace-in-command-mode)
     ;; ("r" . xah-kill-word)
     ;; ("s" . snails-normal-backends)
     ;; ("t" . set-mark-command)
     ;; ("u" . backward-word)
     ;; ("v" . xah-paste-or-paste-previous)
     ;; ("w" . xah-shrink-whitespaces)
     ;; ("x" . xah-cut-line-or-region)
     ;; ("y" . undo)
     ;; ("z" . weiss-xah-comment-dwim)
     )))
  ;; :bind
  ;; (
  ;; :map telega-chat-mode-map
  ;; ("j" . 'telega-button-forward)
  ;; ("k" . 'telega-button-backward)
  ;; ("K" . 'telega-msg-delete-marked-or-at-point)
  ;; ("j" . telega-button-forward)
  ;; )
  )
