(clear-abbrev-table global-abbrev-table)

(define-abbrev-table 'global-abbrev-table
  '(
    ("ws" "weiss" xah-elisp--ahf)
    ))

(when (boundp 'telega-chat-mode-abbrev-table)
  (clear-abbrev-table telega-chat-mode-abbrev-table))

(define-abbrev-table 'telega-chat-mode-abbrev-table
  '(
    ("zj" ":joy:")
    )
  )

(defun weiss-abbrevs-run ()
  "Run abbrevs"
  (interactive)
  (when (boundp 'xah-elisp-mode-abbrev-table)
    (clear-abbrev-table xah-elisp-mode-abbrev-table))

  (define-abbrev-table 'xah-elisp-mode-abbrev-table
    '(

      ("c" "concat" xah-elisp--ahf)
      ("d" "defun" xah-elisp--ahf)
      ("f" "format" xah-elisp--ahf)
      ("i" "insert" xah-elisp--ahf)
      ("l" "let" xah-elisp--ahf)
      ("m" "message" xah-elisp--ahf)
      ("o" "&optional " xah-elisp--ahf)
      ("p" "point" xah-elisp--ahf)
      ("s" "setq" xah-elisp--ahf)
      ("w" "when" xah-elisp--ahf)


      ("ah" "add-hook" xah-elisp--ahf)
      ("al" "add-to-list" xah-elisp--ahf)
      ("bc" "backward-char" xah-elisp--ahf)
      ("bs" "buffer-substring" xah-elisp--ahf)
      ("bw" "backward-word" xah-elisp--ahf)
      ("ca" "char-after" xah-elisp--ahf)
      ("cb" "current-buffer" xah-elisp--ahf)
      ("cc" "condition-case" xah-elisp--ahf)
      ("cd" "copy-directory" xah-elisp--ahf)
      ("cf" "copy-file" xah-elisp--ahf)
      ("ci" "call-interactively" xah-elisp--ahf)
      ("cw" "current-word" xah-elisp--ahf)
      ("dc" "delete-char" xah-elisp--ahf)
      ("dd" "delete-directory" xah-elisp--ahf)
      ("dl" "dolist" xah-elisp--ahf)
      ("dm" "(deactivate-mark)" xah-elisp--ahf)
      ("df" "delete-file" xah-elisp--ahf)
      ("dk" "define-key" xah-elisp--ahf)
      ("dt" "dotimes" xah-elisp--ahf)
      ("dr" "delete-region" xah-elisp--ahf)
      ("dv" "defvar" xah-elisp--ahf)
      ("eb" "erase-buffer" xah-elisp--ahf)
      ("fa" "fillarray" xah-elisp--ahf)
      ("fc" "forward-char" xah-elisp--ahf)
      ("ff" "find-file" xah-elisp--ahf)
      ("fl" "forward-line" xah-elisp--ahf)
      ("fw" "forward-word" xah-elisp--ahf)
      ("up" "(use-package ▮)" xah-elisp--ahf)    
      ("gb" "get-buffer" xah-elisp--ahf)
      ("gc" "goto-char" xah-elisp--ahf)
      ("ie" "(ignore-errors ▮)" xah-elisp--ahf)
      ("kb" "kill-buffer" xah-elisp--ahf)
      ("kr" "kill-region" xah-elisp--ahf)
      ("kn" "(kill-new ▮)" xah-elisp--ahf)
      ("la" "looking-at" xah-elisp--ahf)
      ("lb" "looking-back" xah-elisp--ahf)
      ("lc" "left-char" xah-elisp--ahf)
      ("ld" ":load-path \"▮\"\n:Straight nil" xah-elisp--ahf)
      ("mb" "match-beginning" xah-elisp--ahf)
      ("mc" "mapcar" xah-elisp--ahf)
      ("md" "make-directory" xah-elisp--ahf)
      ("me" "match-end" xah-elisp--ahf)
      ("ml" "make-list" xah-elisp--ahf)
      ("ms" "match-string" xah-elisp--ahf)
      ("nl" "(next-line)" xah-elisp--ahf)
      ("mv" "make-vector" xah-elisp--ahf)
      ("ns" "number-sequence" xah-elisp--ahf)
      ("pm" "point-min" xah-elisp--ahf)
      ("pn" "progn" xah-elisp--ahf)
      ("px" "point-max" xah-elisp--ahf)
      ("pv" "(provide '▮)" xah-elisp--ahf)
      ("rb" "region-beginning" xah-elisp--ahf)
      ("rc" "right-char" xah-elisp--ahf)
      ("re" "region-end" xah-elisp--ahf)
      ("rf" "rename-file" xah-elisp--ahf)
      ("rm" "replace-match" xah-elisp--ahf)
      ("rn" "read-number" xah-elisp--ahf)
      ("rq" "regexp-quote" xah-elisp--ahf)
      ("rr" "replace-regexp" xah-elisp--ahf)
      ("rs" "read-string" xah-elisp--ahf)
      ("sb" "search-backward" xah-elisp--ahf)
      ("sc" "shell-command" xah-elisp--ahf)
      ("se" "save-excursion" xah-elisp--ahf)
      ("sf" "search-forward" xah-elisp--ahf)
      ("sm" "string-match" xah-elisp--ahf)
      ("sr" "save-restriction" xah-elisp--ahf)
      ("ss" "split-string" xah-elisp--ahf)
      ("vc" "vconcat" xah-elisp--ahf)
      ("wg" "widget-get" xah-elisp--ahf)
      ("wr" "write-region" xah-elisp--ahf)
      ("wt" "(defun weiss-test ()\n  \"DOCSTRING\"\n  (interactive)\n  ▮)" xah-elisp--ahf)

      ("bfn" "buffer-file-name" xah-elisp--ahf)
      ("bmp" "buffer-modified-p" xah-elisp--ahf)

      ("atf" "append-to-file" xah-elisp--ahf)
      ("bol" "beginning-of-line" xah-elisp--ahf)
      ("cdr" "cdr" xah-elisp--ahf)
      ("cpa" "current-prefix-arg" xah-elisp--ahf)
      ("dfr" "directory-files-recursively" xah-elisp--ahf)
      ("efn" "expand-file-name" xah-elisp--ahf)
      ("eol" "end-of-line" xah-elisp--ahf)
      ("fep" "file-exists-p" xah-elisp--ahf)
      ("fnd" "file-name-directory" xah-elisp--ahf)
      ("fne" "file-name-extension" xah-elisp--ahf)
      ("fnn" "file-name-nondirectory" xah-elisp--ahf)
      ("frn" "file-relative-name" xah-elisp--ahf)
      ("gbc" "get-buffer-create" xah-elisp--ahf)
      ("gnb" "generate-new-buffer" xah-elisp--ahf)
      ("gsk" "global-set-key" xah-elisp--ahf)
      ("ifc" "insert-file-contents" xah-elisp--ahf)
      ("lam" "lambda" xah-elisp--ahf)
      ("lbp" "(line-beginning-position)" xah-elisp--ahf)
      ("len" "length" xah-elisp--ahf)
      ("lep" "(line-end-position)" xah-elisp--ahf)
      ("mlv" "make-local-variable" xah-elisp--ahf)
      ("ntr" "narrow-to-region" xah-elisp--ahf)
      ("nts" "number-to-string" xah-elisp--ahf)
      ("pmi" "point-min" xah-elisp--ahf)
      ("pma" "push-mark" xah-elisp--ahf)
      ("rap" "region-active-p" xah-elisp--ahf)
      ("rdn" "read-directory-name" xah-elisp--ahf)
      ("req" "(require '▮)" xah-elisp--ahf)
      ("rfn" "read-file-name" xah-elisp--ahf)
      ("rsb" "re-search-backward" xah-elisp--ahf)
      ("rsf" "re-search-forward" xah-elisp--ahf)
      ("sbr" "search-backward-regexp" xah-elisp--ahf)
      ("scb" "skip-chars-backward" xah-elisp--ahf)
      ("scf" "skip-chars-forward" xah-elisp--ahf)
      ("sfm" "set-file-modes" xah-elisp--ahf)
      ("sfr" "search-forward-regexp" xah-elisp--ahf)
      ("sqa" "shell-quote-argument" xah-elisp--ahf)
      ("stb" "switch-to-buffer" xah-elisp--ahf)
      ("ste" "(string-equal str1▮ str2)" xah-elisp--ahf)
      ("stn" "string-to-number" xah-elisp--ahf)
      ("tap" "thing-at-point" xah-elisp--ahf)
      ("urp" "use-region-p" xah-elisp--ahf)
      ("wcb" "with-current-buffer" xah-elisp--ahf)
      ("wtb" "with-temp-buffer" xah-elisp--ahf)
      ("wtf" "with-temp-file" xah-elisp--ahf)

      ("botap" "bounds-of-thing-at-point" xah-elisp--ahf)
      ("bsnp" "(buffer-substring-no-properties START▮ END)" xah-elisp--ahf)
      ("daer" "delete-and-extract-region" xah-elisp--ahf)
      ("epam" "(exchange-point-and-mark)" xah-elisp--ahf)
      ("fnse" "file-name-sans-extension" xah-elisp--ahf)
      ("rris" "replace-regexp-in-string" xah-elisp--ahf)
      ("yonp" "yes-or-no-p" xah-elisp--ahf)

      ("abbreviate-file-name" "(abbreviate-file-name ▮)" xah-elisp--ahf)
      ("add-hook" "(add-hook 'HOOK▮ 'FUNCTION)" xah-elisp--ahf)
      ("add-text-properties" "(add-text-properties START▮ END PROPS &optional OBJECT)" xah-elisp--ahf)
      ("add-to-list" "(add-to-list LIST-VAR▮ ELEMENT &optional APPEND COMPARE-FN)" xah-elisp--ahf)
      ("alist-get" "(alist-get key▮ value &optional default)" xah-elisp--ahf)
      ("and" "(and ▮)" xah-elisp--ahf )
      ("append" "(append ▮)" xah-elisp--ahf)
      ("append-to-file" "(append-to-file START▮ END FILENAME)" xah-elisp--ahf)
      ("apply" "(apply ▮)" xah-elisp--ahf)
      ("aref" "(aref ARRAY▮ INDEX)" xah-elisp--ahf)
      ("aset" "(aset ARRAY▮ IDX NEWELT)" xah-elisp--ahf)
      ("ask-user-about-supersession-threat" "(ask-user-about-supersession-threat FILENAME▮)" xah-elisp--ahf)
      ("assoc" "(assoc KEY▮ LIST)" xah-elisp--ahf)
      ("assoc-default" "(assoc-default key▮ alist &optional test default)" xah-elisp--ahf)
      ("assoc-string" "(assoc-string key▮ alist &optional case-fold)" xah-elisp--ahf)
      ("assq" "(assq key▮ alist)" xah-elisp--ahf)
      ("assq-delete-all" "(assq-delete-all key▮ alist)" xah-elisp--ahf)
      ("autoload" "(autoload 'FUNCNAME▮ \"FILENAME\" &optional \"DOCSTRING\" INTERACTIVE TYPE)" xah-elisp--ahf)
      ("backward-char" "(backward-char ▮)" xah-elisp--ahf)
      ("backward-up-list" "(backward-up-list &optional ARG▮ 'ESCAPE-STRINGS 'NO-SYNTAX-CROSSING)" xah-elisp--ahf)
      ("backward-word" "(backward-word ▮)" xah-elisp--ahf)
      ("barf-if-buffer-read-only" "(barf-if-buffer-read-only)" xah-elisp--ahf)
      ("beginning-of-line" "(beginning-of-line)" xah-elisp--ahf)
      ("boundp" "(boundp '▮)" xah-elisp--ahf)
      ("bounds-of-thing-at-point" "(bounds-of-thing-at-point 'symbol▮ 'filename 'word 'whitespace 'line)" xah-elisp--ahf)
      ("buffer-base-buffer" "(buffer-base-buffer &optional BUFFER▮)" xah-elisp--ahf)
      ("buffer-chars-modified-tick" "(buffer-chars-modified-tick &optional BUFFER▮)" xah-elisp--ahf)
      ("buffer-file-name" "(buffer-file-name)" xah-elisp--ahf)
      ("buffer-list" "(buffer-list &optional FRAME▮)" xah-elisp--ahf)
      ("buffer-live-p" "(buffer-live-p OBJECT▮)" xah-elisp--ahf)
      ("buffer-modified-p" "(buffer-modified-p BUFFER▮)" xah-elisp--ahf)
      ("buffer-modified-p" "(buffer-modified-p ▮)" xah-elisp--ahf)
      ("buffer-modified-tick" "(buffer-modified-tick &optional BUFFER▮)" xah-elisp--ahf)
      ("buffer-name" "(buffer-name BUFFER▮)" xah-elisp--ahf)
      ("buffer-substring" "(buffer-substring START▮ END)" xah-elisp--ahf)
      ("buffer-substring-no-properties" "(buffer-substring-no-properties START▮ END)" xah-elisp--ahf)
      ("buffer-swap-text" "(buffer-swap-text BUFFER▮)" xah-elisp--ahf)
      ("bufferp" "(bufferp ▮)" xah-elisp--ahf)
      ("bury-buffer" "(bury-buffer &optional BUFFER-OR-NAME▮)" xah-elisp--ahf)
      ("call-interactively" "(call-interactively 'FUNCTION▮ &optional RECORD-FLAG KEYS)" xah-elisp--ahf)
      ("called-interactively-p" "(called-interactively-p 'interactive▮)" xah-elisp--ahf)
      ("car" "(car ▮)" xah-elisp--ahf)
      ("catch" "(catch 'TAG▮ BODY)" xah-elisp--ahf)
      ("cdr" "(cdr ▮)" xah-elisp--ahf)
      ("char-after" "(char-after &optional ▮POS)" xah-elisp--ahf)
      ("char-before" "(char-before &optional ▮POS)" xah-elisp--ahf)
      ("char-equal" "(char-equal char1▮ char1)" xah-elisp--ahf)
      ("char-to-string" "(char-to-string CHAR▮) " xah-elisp--ahf)
      ("clear-image-cache" "(clear-image-cache &optional FILTER▮)" xah-elisp--ahf)
      ("clear-visited-file-modtime" "(clear-visited-file-modtime)" xah-elisp--ahf)
      ("clone-indirect-buffer" "(clone-indirect-buffer NEWNAME▮ DISPLAY-FLAG &optional NORECORD)" xah-elisp--ahf)
      ("clrhash" "(clrhash ▮)" xah-elisp--ahf)
      ("compare-strings" "(compare-strings string1▮ start1 end1 string2 start2 end2)" xah-elisp--ahf)
      ("concat" "(concat \"▮\" \"\")" xah-elisp--ahf)
      ("cond" "(cond\n(CONDITION▮ BODY)\n(CONDITION BODY)\n)" xah-elisp--ahf)
      ("condition-case" "(condition-case ▮)" xah-elisp--ahf)
      ("cons" "(cons CAR▮ CDR)" xah-elisp--ahf)
      ("consp" "(consp ▮)" xah-elisp--ahf)
      ("constrain-to-field" "(constrain-to-field NEW-POS▮ OLD-POS &optional ESCAPE-FROM-EDGE ONLY-IN-LINE INHIBIT-CAPTURE-PROPERTY)" xah-elisp--ahf)
      ("copy-alist" "(copy-alist alist▮)" xah-elisp--ahf)
      ("copy-directory" "(copy-directory ▮ NEWNAME &optional KEEP-TIME PARENTS)" xah-elisp--ahf)
      ("copy-file" "(copy-file FILE▮ NEWNAME &optional OK-IF-ALREADY-EXISTS KEEP-TIME PRESERVE-UID-GID)" xah-elisp--ahf)
      ("create-image" "(create-image FILE-OR-DATA▮ &optional TYPE DATA-P &rest)" xah-elisp--ahf)
      ("cts" "(char-to-string CHAR▮) " xah-elisp--ahf)
      ("current-buffer" "(current-buffer)" xah-elisp--ahf)
      ("current-word" "(current-word)" xah-elisp--ahf)
      ("custom-autoload" "(custom-autoload ▮ SYMBOL LOAD &optional NOSET)" xah-elisp--ahf)
      ("defalias" "(defalias 'SYMBOL▮ 'DEFINITION &optional DOCSTRING)" xah-elisp--ahf)
      ("defconst" "(defconst ▮ INITVALUE \"DOCSTRING\")" xah-elisp--ahf)
      ("defcustom" "(defcustom ▮ VALUE \"DOC\" &optional ARGS)" xah-elisp--ahf)
      ("defface" "(defface FACE▮ SPEC \"DOC\" &rest ARGS)" xah-elisp--ahf)
      ("defimage" "(defimage SYMBOL▮ SPECS &optional DOC)" xah-elisp--ahf)
      ("define-key" "(define-key KEYMAPNAME▮ (kbd \"M-b\") 'FUNCNAME)" xah-elisp--ahf)
      ("define-minor-mode" "(define-minor-mode MODE▮ \"DOC\" &optional INIT-VALUE LIGHTER KEYMAP &rest BODY)" xah-elisp--ahf)
      ("defsubst" "(defsubst ▮)" xah-elisp--ahf)
      ("defun" "(defun ▮ ()\n  \"DOCSTRING\"\n  (interactive)\n  (let (())\n\n ))" xah-elisp--ahf)
      ("defvar" "(defvar ▮ &optional INITVALUE \"DOCSTRING\")" xah-elisp--ahf)
      ("delete" "(delete OBJECT▮ SEQUENCE)" xah-elisp--ahf)
      ("delete-and-extract-region" "(delete-and-extract-region ▮ pos2)" xah-elisp--ahf)
      ("delete-char" "(delete-char 1▮)" xah-elisp--ahf)
      ("delete-directory" "(delete-directory ▮ &optional RECURSIVE)" xah-elisp--ahf)
      ("delete-dups" "(delete-dups LIST▮)" xah-elisp--ahf)
      ("delete-field" "(delete-field &optional POS▮)" xah-elisp--ahf)
      ("delete-file" "(delete-file ▮)" xah-elisp--ahf)
      ("delete-region" "(delete-region pos1▮ pos2)" xah-elisp--ahf)
      ("delq" "(delq ELT▮ LIST)" xah-elisp--ahf)
      ("directory-file-name" "(directory-file-name ▮)" xah-elisp--ahf)
      ("directory-files" "(directory-files ▮ &optional FULL MATCH NOSORT)" xah-elisp--ahf)
      ("directory-files-recursively" "(directory-files-recursively DIR▮ REGEXP &optional INCLUDE-DIRECTORIES)" xah-elisp--ahf)
      ("directory-name-p" "(directory-name-p ▮)" xah-elisp--ahf)
      ("dolist" "(dolist (x LIST▮ [RESULT]) BODY)" xah-elisp--ahf)
      ("dotimes" "(dotimes (i COUNT▮ [RESULT]) BODY)" xah-elisp--ahf)
      ("elt" "(elt SEQUENCE▮ N)" xah-elisp--ahf)
      ("end-of-line" "(end-of-line ▮&optional N)" xah-elisp--ahf)
      ("eq" "(eq ▮)" xah-elisp--ahf)
      ("equal" "(equal ▮)" xah-elisp--ahf)
      ("erase-buffer" "(erase-buffer)" xah-elisp--ahf)
      ("error" "(error \"%s\" ▮)" xah-elisp--ahf)
      ("expand-file-name" "(expand-file-name ▮ &optional relativedir)" xah-elisp--ahf)
      ("fboundp" "(fboundp '▮)" xah-elisp--ahf)
      ("featurep" "(featurep 'FEATURE▮)" xah-elisp--ahf)
      ("field-beginning" "(field-beginning &optional POS▮ ESCAPE-FROM-EDGE LIMIT)" xah-elisp--ahf)
      ("field-end" "(field-end &optional POS▮ ESCAPE-FROM-EDGE LIMIT)" xah-elisp--ahf)
      ("field-string" "(field-string &optional POS▮)" xah-elisp--ahf)
      ("field-string-no-properties" "(field-string-no-properties &optional POS▮)" xah-elisp--ahf)
      ("file-directory-p" "(file-directory-p ▮)" xah-elisp--ahf)
      ("file-exists-p" "(file-exists-p ▮)" xah-elisp--ahf)
      ("file-name-absolute-p" "(file-name-absolute-p ▮)" xah-elisp--ahf)
      ("file-name-as-directory" "(file-name-as-directory ▮)" xah-elisp--ahf)
      ("file-name-directory" "(file-name-directory ▮)" xah-elisp--ahf)
      ("file-name-extension" "(file-name-extension ▮ &optional PERIOD)" xah-elisp--ahf)
      ("file-name-nondirectory" "(file-name-nondirectory ▮)" xah-elisp--ahf)
      ("file-name-sans-extension" "(file-name-sans-extension ▮)" xah-elisp--ahf)
      ("file-regular-p" "(file-regular-p ▮)" xah-elisp--ahf)
      ("file-relative-name" "(file-relative-name ▮)" xah-elisp--ahf)
      ("find-buffer-visiting" "(find-buffer-visiting FILENAME▮ &optional PREDICATE)" xah-elisp--ahf)
      ("find-file" "(find-file ▮)" xah-elisp--ahf)
      ("find-image" "(find-image SPECS▮)" xah-elisp--ahf)
      ("font-lock-add-keywords" "(font-lock-add-keywords MODE▮ KEYWORDS &optional HOW)" xah-elisp--ahf)
      ("font-lock-fontify-buffer" "(font-lock-fontify-buffer ▮)" xah-elisp--ahf)
      ("format" "(format \"%s\" ▮)" xah-elisp--ahf)
      ;; ("format" "(format \"▮\" &optional OBJECTS)" xah-elisp--ahf)
      ("forward-char" "(forward-char ▮)" xah-elisp--ahf)
      ("forward-line" "(forward-line ▮)" xah-elisp--ahf)
      ("forward-word" "(forward-word ▮)" xah-elisp--ahf)
      ("funcall" "(funcall 'FUNCTION▮ &rest ARGUMENTS)" xah-elisp--ahf)
      ("function" "(function ▮)" xah-elisp--ahf)
      ("gap-position" "(gap-position)" xah-elisp--ahf)
      ("gap-size" "(gap-size)" xah-elisp--ahf)
      ("generate-new-buffer" "(generate-new-buffer NAME▮)" xah-elisp--ahf)
      ("generate-new-buffer" "(generate-new-buffer ▮)" xah-elisp--ahf)
      ("generate-new-buffer-name" "(generate-new-buffer-name STARTING-NAME▮ &optional IGNORE)" xah-elisp--ahf)
      ("get" "(get SYMBOL▮ 'PROPNAME)" xah-elisp--ahf)
      ("get-buffer" "(get-buffer BUFFER-OR-NAME▮)" xah-elisp--ahf)
      ("get-buffer-create" "(get-buffer-create BUFFER-OR-NAME▮)" xah-elisp--ahf)
      ("get-char-code-property" "(get-char-code-property CHAR▮ PROPNAME)" xah-elisp--ahf)
      ("get-char-property" "(get-char-property POSITION▮ PROP &optional OBJECT)" xah-elisp--ahf)
      ("get-char-property-and-overlay" "(get-char-property-and-overlay POSITION▮ PROP &optional)" xah-elisp--ahf)
      ("get-file-buffer" "(get-file-buffer FILENAME▮)" xah-elisp--ahf)
      ("get-pos-property" "(get-pos-property POSITION▮ PROP &optional OBJECT)" xah-elisp--ahf)
      ("get-text-property" "(get-text-property POS▮ PROP &optional OBJECT)" xah-elisp--ahf)
      ("gethash" "(gethash KEY▮ TABLE &optional DFLT)" xah-elisp--ahf)
      ("global-set-key" "(global-set-key (kbd \"C-▮\") 'COMMAND)" xah-elisp--ahf)
      ("goto-char" "(goto-char ▮)" xah-elisp--ahf)
      ("if" "(if ▮\n    (progn )\n  (progn )\n)" xah-elisp--ahf)
      ("image-flush" "(image-flush SPEC▮ &optional FRAME)" xah-elisp--ahf)
      ("image-load-path-for-library" "(image-load-path-for-library LIBRARY▮ IMAGE &optional PATH)" xah-elisp--ahf)
      ("image-size" "(image-size SPEC▮ &optional PIXELS FRAME)" xah-elisp--ahf)
      ("insert" "(insert ▮)" xah-elisp--ahf)
      ("insert-and-inherit" "(insert-and-inherit ▮)" xah-elisp--ahf)
      ("insert-before-markers-and-inherit" "(insert-before-markers-and-inherit ▮)" xah-elisp--ahf)
      ("insert-char" "(insert-char CHARACTER▮ &optional COUNT INHERIT)" xah-elisp--ahf)
      ("insert-file-contents" "(insert-file-contents ▮ &optional VISIT BEG END REPLACE)" xah-elisp--ahf)
      ("insert-image" "(insert-image IMAGE▮ &optional STRING AREA SLICE)" xah-elisp--ahf)
      ("insert-sliced-image" "(insert-sliced-image IMAGE▮ &optional STRING AREA ROWS COLS)" xah-elisp--ahf)
      ("interactive" "(interactive)" xah-elisp--ahf)
      ("kbd" "(kbd \"▮\")" xah-elisp--ahf)
      ("kill-append" "(kill-append STRING▮ BEFORE-P)" xah-elisp--ahf)
      ("kill-buffer" "(kill-buffer &optional BUFFER-OR-NAME▮)" xah-elisp--ahf)
      ("kill-buffer" "(kill-buffer ▮)" xah-elisp--ahf)
      ("kill-region" "(kill-region BEG▮ END &optional REGION)" xah-elisp--ahf)
      ("lambda" "(lambda (x▮) BODY)" xah-elisp--ahf)
      ("last-buffer" "(last-buffer &optional BUFFER▮ VISIBLE-OK FRAME)" xah-elisp--ahf)
      ("left-char" "(left-char ▮)" xah-elisp--ahf)
      ("length" "(length ▮)" xah-elisp--ahf)
      ("let" "(let ((▮))\n \n)" xah-elisp--ahf)
      ("let*" "(let* (▮)\n x\n)" xah-elisp--ahf)
      ("line-beginning-position" "(line-beginning-position)" xah-elisp--ahf)
      ("line-end-position" "(line-end-position)" xah-elisp--ahf)
      ("list" "(list ▮)" xah-elisp--ahf)
      ("load" "(load FILE▮ &optional NOERROR NOMESSAGE NOSUFFIX MUST-SUFFIX)" xah-elisp--ahf)
      ("load-file" "(load-file FILE▮)" xah-elisp--ahf)
      ("looking-at" "(looking-at \"REGEXP▮\")" xah-elisp--ahf)
      ("looking-back" "(looking-back \"REGEXP▮\" LIMIT &optional GREEDY)" xah-elisp--ahf)
      ("make-directory" "(make-directory ▮ &optional PARENTS)" xah-elisp--ahf)
      ("make-hash-table" "(make-hash-table :test 'equal ▮ &rest KEYWORD-ARGS)" xah-elisp--ahf)
      ("make-indirect-buffer" "(make-indirect-buffer BASE-BUFFER▮ NAME &optional CLONE)" xah-elisp--ahf)
      ("make-list" "(make-list LENGTH▮ INIT)" xah-elisp--ahf)
      ("make-local-variable" "(make-local-variable ▮)" xah-elisp--ahf)
      ("make-string" "(make-string count character)" xah-elisp--ahf)
      ("mapc" "(mapc '▮ SEQUENCE)" xah-elisp--ahf)
      ("mapcar" "(mapcar '▮ SEQUENCE)" xah-elisp--ahf)
      ("mapconcat" "(mapconcat FUNCTION▮ SEQUENCE SEPARATOR)" xah-elisp--ahf)
      ("maphash" "(maphash FUNCTION▮ TABLE)" xah-elisp--ahf)
      ("match-beginning" "(match-beginning N▮)" xah-elisp--ahf)
      ("match-data" "(match-data &optional INTEGERS▮ REUSE RESEAT)" xah-elisp--ahf)
      ("match-end" "(match-end N▮)" xah-elisp--ahf)
      ("match-string" "(match-string NUM▮ &optional STRING)" xah-elisp--ahf)
      ("member" "(member ELT▮ LIST)" xah-elisp--ahf)
      ("member" "(member OBJECT▮ LIST)" xah-elisp--ahf)
      ("member-ignore-case" "(member-ignore-case OBJECT▮ LIST)" xah-elisp--ahf)
      ("memq" "(memq ELT▮ LIST)" xah-elisp--ahf)
      ("memql" "(memql OBJECT▮ LIST)" xah-elisp--ahf)
      ("message" "(message \"%s\" ▮)" xah-elisp--ahf)
      ("narrow-to-region" "(narrow-to-region START▮ END)" xah-elisp--ahf)
      ("next-char-property-change" "(next-char-property-change POS &optional LIMIT)" xah-elisp--ahf)
      ("next-property-change" "(next-property-change POS &optional OBJECT LIMIT)" xah-elisp--ahf)
      ("next-single-char-property-change" "(next-single-char-property-change POS PROP &optional OBJECT LIMIT)" xah-elisp--ahf)
      ("next-single-property-change" "(next-single-property-change POS PROP &optional OBJECT LIMIT)" xah-elisp--ahf)
      ("not" "(not ▮)" xah-elisp--ahf)
      ("not-modified" "(not-modified &optional ARG▮)" xah-elisp--ahf)
      ("nth" "(nth N▮ LIST)" xah-elisp--ahf)
      ("null" "(null ▮)" xah-elisp--ahf)
      ("number-sequence" "(number-sequence FROM▮ &optional TO INC)" xah-elisp--ahf)
      ("number-to-string" "(number-to-string ▮)" xah-elisp--ahf)
      ("or" "(or ▮)" xah-elisp--ahf)
      ("other-buffer" "(other-buffer &optional BUFFER▮ VISIBLE-OK FRAME)" xah-elisp--ahf)
      ("point" "(point)" xah-elisp--ahf)
      ("point-max" "(point-max)" xah-elisp--ahf)
      ("point-min" "(point-min)" xah-elisp--ahf)
      ("pop" "(pop ▮)" xah-elisp--ahf)
      ("previous-char-property-change" "(previous-char-property-change POS &optional LIMIT)" xah-elisp--ahf)
      ("previous-property-change" "(previous-property-change POS &optional OBJECT LIMIT)" xah-elisp--ahf)
      ("previous-single-char-property-change" "(previous-single-char-property-change POS PROP &optional OBJECT LIMIT)" xah-elisp--ahf)
      ("previous-single-property-change" "(previous-single-property-change POS PROP &optional OBJECT LIMIT)" xah-elisp--ahf)
      ("prin1" "(prin1 ▮)" xah-elisp--ahf)
      ("prin1-to-string" "(prin1-to-string▮ OBJECT &optional NOESCAPE)" xah-elisp--ahf)
      ("princ" "(princ ▮)" xah-elisp--ahf)
      ("print" "(print ▮)" xah-elisp--ahf)
      ("prog1" "(prog1\n▮)" xah-elisp--ahf)
      ("prog2" "(prog2\n▮)" xah-elisp--ahf)
      ("progn" "(progn\n▮)" xah-elisp--ahf)
      ("propertize" "(propertize STRING▮ &rest PROPERTIES)" xah-elisp--ahf)
      ("push" "(push NEWELT▮ PLACE)" xah-elisp--ahf)
      ("push-mark" "(push-mark ▮ &optional LOCATION NOMSG ACTIVATE)" xah-elisp--ahf)
      ("put" "(put 'SYMBOL▮ 'PROPNAME VALUE)" xah-elisp--ahf)
      ("put-image" "(put-image IMAGE▮ POS &optional STRING AREA)" xah-elisp--ahf)
      ("put-text-property" "(put-text-property START▮ END PROP VALUE &optional OBJECT)" xah-elisp--ahf)
      ("puthash" "(puthash KEY▮ VALUE TABLE)" xah-elisp--ahf)
      ("random" "(random ▮)" xah-elisp--ahf)
      ("rassoc" "(rassoc KEY▮ LIST)" xah-elisp--ahf)
      ("rassoc" "(rassoc value▮ alist)" xah-elisp--ahf)
      ("rassq" "(rassq value▮ alist)" xah-elisp--ahf)
      ("rassq-delete-all" "(rassq-delete-all value▮ alist)" xah-elisp--ahf)
      ("re-search-backward" "(re-search-backward \"REGEXP▮\" &optional BOUND NOERROR COUNT)" xah-elisp--ahf)
      ("re-search-forward" "(re-search-forward \"REGEXP▮\" &optional BOUND NOERROR COUNT)" xah-elisp--ahf)
      ("read-directory-name" "(read-directory-name \"Dir▮:\" &optional DIR DEFAULT-DIRNAME MUSTMATCH INITIAL)" xah-elisp--ahf)
      ("read-file-name" "(read-file-name \"▮\" &optional DIR DEFAULT-FILENAME MUSTMATCH INITIAL PREDICATE)" xah-elisp--ahf)
      ("read-regexp" "(read-regexp \"Type regex▮:\" &optional DEFAULT-VALUE)" xah-elisp--ahf)
      ("read-string" "(read-string \"What▮:\" &optional INITIAL-INPUT HISTORY DEFAULT-VALUE INHERIT-INPUT-METHOD)" xah-elisp--ahf)
      ("read-number" "(read-number \"Number▮:\" DEFAULT?)" xah-elisp--ahf)
      ("regexp-opt" "(regexp-opt STRINGS▮ &optional PAREN)" xah-elisp--ahf)
      ("regexp-quote" "(regexp-quote ▮)" xah-elisp--ahf)
      ("region-active-p" "(region-active-p)" xah-elisp--ahf)
      ("region-beginning" "(region-beginning)" xah-elisp--ahf)
      ("region-end" "(region-end)" xah-elisp--ahf)
      ("remhash" "(remhash KEY▮ TABLE)" xah-elisp--ahf)
      ("remove" "(remove OBJECT▮ SEQUENCE)" xah-elisp--ahf)
      ("remove-images" "(remove-images START▮ END &optional BUFFER)" xah-elisp--ahf)
      ("remove-list-of-text-properties" "(remove-list-of-text-properties START▮ END LIST OF PROPERTIES &optional OBJECT)" xah-elisp--ahf)
      ("remove-text-properties" "(remove-text-properties START▮ END PROPS &optional OBJECT)" xah-elisp--ahf)
      ("remq" "(remq OBJECT▮ LIST)" xah-elisp--ahf)
      ("rename-buffer" "(rename-buffer NEWNAME▮ &optional UNIQUE)" xah-elisp--ahf)
      ("rename-file" "(rename-file FILE▮ NEWNAME &optional OK-IF-ALREADY-EXISTS)" xah-elisp--ahf)
      ("repeat" "(repeat ▮)" xah-elisp--ahf)
      ("replace-match" "(replace-match NEWTEXT▮ &optional FIXEDCASE LITERAL \"STRING\" SUBEXP)" xah-elisp--ahf)
      ("replace-regexp" "(replace-regexp \"REGEXP▮\" TO-STRING &optional DELIMITED START END)" xah-elisp--ahf)
      ("replace-regexp-in-string" "(replace-regexp-in-string \"REGEXP▮\" REP \"STRING\" &optional FIXEDCASE LITERAL SUBEXP START)" xah-elisp--ahf)
      ;; ("require" "(require ▮)" xah-elisp--ahf)
      ("restore-buffer-modified-p" "(restore-buffer-modified-p FLAG▮)" xah-elisp--ahf)
      ("reverse" "(reverse ▮)" xah-elisp--ahf)
      ("right-char" "(right-char ▮)" xah-elisp--ahf)
      ("run-with-timer" "(run-with-timer SECS▮ REPEAT FUNCTION &rest ARGS)" xah-elisp--ahf)
      ("save-buffer" "(save-buffer &optional ARG▮)" xah-elisp--ahf)
      ("save-current-buffer" "(save-current-buffer ▮)" xah-elisp--ahf)
      ("save-excursion" "(save-excursion ▮)" xah-elisp--ahf)
      ("save-restriction" "(save-restriction ▮)" xah-elisp--ahf)
      ("search-backward" "(search-backward \"▮\" &optional BOUND NOERROR COUNT)" xah-elisp--ahf)
      ("search-backward-regexp" "(search-backward-regexp \"▮\" &optional BOUND NOERROR COUNT)" xah-elisp--ahf)
      ("search-forward" "(search-forward \"▮\" &optional BOUND NOERROR COUNT)" xah-elisp--ahf)
      ("search-forward-regexp" "(search-forward-regexp \"▮\" &optional BOUND NOERROR COUNT)" xah-elisp--ahf)
      ("set-buffer" "(set-buffer ▮)" xah-elisp--ahf)
      ("set-buffer-modified-p" "(set-buffer-modified-p FLAG▮)" xah-elisp--ahf)
      ("set-file-modes" "(set-file-modes ▮ MODE)" xah-elisp--ahf)
      ("set-mark" "(set-mark ▮)" xah-elisp--ahf)
      ("set-syntax-table" "(set-syntax-table ▮)" xah-elisp--ahf)
      ("set-text-properties" "(set-text-properties START▮ END PROPS &optional OBJECT)" xah-elisp--ahf)
      ("set-visited-file-modtime" "(set-visited-file-modtime &optional TIME▮)" xah-elisp--ahf)
      ("set-visited-file-name" "(set-visited-file-name FILENAME▮ &optional NO-QUERY ALONG-WITH-FILE)" xah-elisp--ahf)
      ("setq" "(setq ▮)" xah-elisp--ahf)
      ("max" "(max ▮)" xah-elisp--ahf)
      ("shell-command" "(shell-command ▮ &optional OUTPUT-BUFFER ERROR-BUFFER)" xah-elisp--ahf)
      ("shell-quote-argument" "(shell-quote-argument ▮)" xah-elisp--ahf)
      ("skip-chars-backward" "(skip-chars-backward \"▮\" &optional LIM)" xah-elisp--ahf)
      ("skip-chars-forward" "(skip-chars-forward \"▮\" &optional LIM)" xah-elisp--ahf)
      ("split-string" "(split-string ▮ &optional SEPARATORS OMIT-NULLS)" xah-elisp--ahf)
      ("stc" "(string-to-char \"▮\")" xah-elisp--ahf)
      ("string-collate-equalp" "(string-collate-equalp string1▮ string2 &optional locale)" xah-elisp--ahf)
      ("string-collate-lessp" "(string-collate-lessp string1▮ string2 &optional locale)" xah-elisp--ahf)
      ("string-equal" "(string-equal str1▮ str2)" xah-elisp--ahf)
      ("string-greaterp" "(string-greaterp string1▮ string2)" xah-elisp--ahf)
      ("string-lessp" "(string-lessp string1▮ string2)" xah-elisp--ahf)
      ("string-match" "(string-match \"REGEXP▮\" \"STRING\" &optional START)" xah-elisp--ahf)
      ("string-match-p" "(string-match-p \"REGEXP▮\" \"STRING\" &optional START)" xah-elisp--ahf)
      ("string-prefix-p" "(string-prefix-p prefixstr▮ string2 &optional ignore-case)" xah-elisp--ahf)
      ("string-prefix-p" "(string-prefix-p string1▮ string2 &optional ignore-case)" xah-elisp--ahf)
      ("string-suffix-p" "(string-suffix-p suffix▮ string &optional ignore-case)" xah-elisp--ahf)
      ("string-suffix-p" "(string-suffix-p suffix▮ string &optional ignore-case)" xah-elisp--ahf)
      ("string-to-char" "(string-to-char \"▮\")" xah-elisp--ahf)
      ("string-to-number" "(string-to-number \"▮\")" xah-elisp--ahf)
      ("string=" "(string-equal str1▮ str2)" xah-elisp--ahf)
      ("stringp" "(stringp ▮)" xah-elisp--ahf)
      ("substring" "(substring STRING▮ FROM &optional TO)" xah-elisp--ahf)
      ("substring-no-properties" "(substring-no-properties ▮ FROM TO)" xah-elisp--ahf)
      ("switch-to-buffer" "(switch-to-buffer ▮ &optional NORECORD FORCE-SAME-WINDOW)" xah-elisp--ahf)
      ("terpri" "(terpri ▮)" xah-elisp--ahf)
      ("text-properties-at" "(text-properties-at POSITION▮ &optional OBJECT)" xah-elisp--ahf)
      ("text-property-any" "(text-property-any START END PROP VALUE &optional OBJECT)" xah-elisp--ahf)
      ("text-property-not-all" "(text-property-not-all START END PROP VALUE &optional OBJECT)" xah-elisp--ahf)
      ("thing-at-point" "(thing-at-point 'word▮ 'symbol 'list 'sexp 'defun 'filename 'url 'email 'sentence 'whitespace 'line 'number 'page)" xah-elisp--ahf)
      ("throw" "(throw 'TAG▮ VALUE)" xah-elisp--ahf)
      ("toggle-read-only" "(toggle-read-only &optional ARG▮)" xah-elisp--ahf)
      ("unbury-buffer" "(unbury-buffer)" xah-elisp--ahf)
      ("unless" "(unless ▮)" xah-elisp--ahf)
      ("use-region-p" "(use-region-p)" xah-elisp--ahf)
      ("user-error" "(user-error \"%s▮\" &rest ARGS)" xah-elisp--ahf)
      ("vector" "(vector ▮)" xah-elisp--ahf)
      ("verify-visited-file-modtime" "(verify-visited-file-modtime BUFFER▮)" xah-elisp--ahf)
      ("version<" "(version< \"24.4\" emacs-version)" xah-elisp--ahf )
      ("version<=" "(version<= \"24.4\" emacs-version)" xah-elisp--ahf )
      ("visited-file-modtime" "(visited-file-modtime)" xah-elisp--ahf)
      ("when" "(when ▮)" xah-elisp--ahf)
      ("while" "(while (▮)\n  (setq ))" xah-elisp--ahf)
      ("widen" "(widen)" xah-elisp--ahf)
      ("widget-get" "(widget-get ▮)" xah-elisp--ahf)
      ("with-current-buffer" "(with-current-buffer BUFFER-OR-NAME▮ BODY)" xah-elisp--ahf)
      ("with-output-to-string" "(with-output-to-string BODY▮)" xah-elisp--ahf)
      ("with-output-to-temp-buffer" "(with-output-to-temp-buffer BUFNAME▮ &rest BODY)" xah-elisp--ahf)
      ("with-temp-buffer" "(with-temp-buffer ▮)" xah-elisp--ahf)
      ("with-temp-file" "(with-temp-file FILE▮ BODY)" xah-elisp--ahf)
      ("write-char" "(write-char CHARACTER▮ &optional STREAM)" xah-elisp--ahf)
      ("write-file" "(write-file FILENAME▮ &optional CONFIRM)" xah-elisp--ahf)
      ("write-region" "(write-region (point-min) (point-max) FILENAME▮ &optional APPEND VISIT LOCKNAME MUSTBENEW)" xah-elisp--ahf)
      ("y-or-n-p" "(y-or-n-p \"PROMPT▮ \")" xah-elisp--ahf)
      ("yes-or-no-p" "(yes-or-no-p \"PROMPT▮ \")" xah-elisp--ahf)

      ("make-vector" "(make-vector 5▮ 0)" xah-elisp--ahf)
      ("vconcat" "(vconcat SEQUENCES▮)" xah-elisp--ahf)
      ("fillarray" "(fillarray ARRAY▮ 0)" xah-elisp--ahf)

      ;;
      )

    "Abbrev table for `xah-elisp-mode'"
    )
  )

(weiss-abbrevs-run)
(set-default 'abbrev-mode t)
(setq save-abbrevs nil)

(add-hook 'xah-elisp-mode-hook 'weiss-abbrevs-run)

(provide 'weiss_abbrevs)
