(defmacro wks-create-function (name functions)
  `(defun ,name ()
     "auto generated by wks-create-function"
     (interactive)
     (dolist (x ',functions) (eval x))
     )
  )

(defun wks-define-key (keymap prefix key-cmd-alist)
  "DOCSTRING"
  (interactive)
  (mapc
   (lambda (pair)
     (if (listp (cdr pair))
         (let ((name (cadr pair))
               (functions (cddr pair))
               )
           (eval `(wks-create-function ,name ,functions))             
           (define-key keymap (kbd (concat prefix (car pair))) name)
           )
       (define-key keymap (kbd (concat prefix (car pair))) (cdr pair))
       )
     )
   key-cmd-alist)
  )

;; (global-unset-key (kbd "t"))
;; (wks-define-key
;;  global-map ""
;;  `(
;;    ("t e" . (weiss-execute-te (execute-kbd-macro ,(kbd "C-c '"))))
;;    ("t u" . (weiss-execute-tu (insert "asdf"))))
;;  )

;; (apply '(message "left char"))
;; (require 'weiss_ui<wks)
;; (require 'weiss_insert-mode<wks)
;; (provide 'weiss_core<wks)
